<?php

namespace Database\Seeders;

use App\Actions\ImportProvincesAction;
use App\Models\Province;
use Illuminate\Database\Seeder;

class ProvinceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        ImportProvincesAction::run();

        // $provinces = [
        //     ['name' => 'Agrigento', 'code' => 'AG', 'region_id' => 1],
        //     ['name' => 'Alessandria', 'code' => 'AL', 'region_id' => 2],
        //     ['name' => 'Ancona', 'code' => 'AN', 'region_id' => 3],
        //     ['name' => 'Aosta', 'code' => 'AO', 'region_id' => 4],
        //     ['name' => 'Arezzo', 'code' => 'AR', 'region_id' => 5],
        //     ['name' => 'Ascoli Piceno', 'code' => 'AP', 'region_id' => 3],
        //     ['name' => 'Asti', 'code' => 'AT', 'region_id' => 2],
        //     ['name' => 'Avellino', 'code' => 'AV', 'region_id' => 6],
        //     ['name' => 'Bari', 'code' => 'BA', 'region_id' => 7],
        //     ['name' => 'Barletta-Andria-Trani', 'code' => 'BT', 'region_id' => 7],
        //     ['name' => 'Belluno', 'code' => 'BL', 'region_id' => 8],
        //     ['name' => 'Benevento', 'code' => 'BN', 'region_id' => 6],
        //     ['name' => 'Bergamo', 'code' => 'BG', 'region_id' => 9],
        //     ['name' => 'Biella', 'code' => 'BI', 'region_id' => 2],
        //     ['name' => 'Bologna', 'code' => 'BO', 'region_id' => 10],
        //     ['name' => 'Bolzano', 'code' => 'BZ', 'region_id' => 11],
        //     ['name' => 'Brescia', 'code' => 'BS', 'region_id' => 9],
        //     ['name' => 'Brindisi', 'code' => 'BR', 'region_id' => 7],
        //     ['name' => 'Cagliari', 'code' => 'CA', 'region_id' => 12],
        //     ['name' => 'Caltanissetta', 'code' => 'CL', 'region_id' => 1],
        //     ['name' => 'Campobasso', 'code' => 'CB', 'region_id' => 13],
        //     ['name' => 'Carbonia-Iglesias', 'code' => 'CI', 'region_id' => 12],
        //     ['name' => 'Caserta', 'code' => 'CE', 'region_id' => 6],
        //     ['name' => 'Catania', 'code' => 'CT', 'region_id' => 1],
        //     ['name' => 'Catanzaro', 'code' => 'CZ', 'region_id' => 14],
        //     ['name' => 'Chieti', 'code' => 'CH', 'region_id' => 15],
        //     ['name' => 'Como', 'code' => 'CO', 'region_id' => 9],
        //     ['name' => 'Cosenza', 'code' => 'CS', 'region_id' => 14],
        //     ['name' => 'Cremona', 'code' => 'CR', 'region_id' => 10],
        //     ['name' => "Crotone", "code" =>'KR','region_id'=>14],
        //     ['name'=>'Cuneo','code'=>'CN','region_id'=>2],
        //     ['name'=>'Enna','code'=>'EN','region_id'=>1],
        //     ['name'=>'Fermo','code'=>'FM','region_id'=>3],
        //     ['name'=>'Ferrara','code'=>'FE','region_id'=>10],
        //     ['name'=>'Firenze','code'=>'FI','region_id'=>5],
        //     ['name'=>'Foggia','code'=>'FG','region_id'=>7],
        //     ['name'=>'Forlì-Cesena','code'=>'FC','region_id'=>10],
        //     ['name'=>'Frosinone','code'=>'FR','region_id'=>15],
        //     ['name'=>'Genova','code'=>'GE','region_id'=>2],
        //     ['name'=>'Gorizia','code'=>'GO','region_id'=>11],
        //     ['name'=>'Grosseto','code'=>'GR','region_id'=>5],
        //     ['name'=>'Imperia','code'=>'IM','region_id'=>2],
        //     ['name'=>'Isernia','code'=>'IS','region_id'=>13],
        //     ['name'=>'La Spezia','code'=>'SP','region_id'=>2],
        //     ['name'=>'L\'Aquila','code'=>'AQ','region_id'=>15],
        //     ['name'=>'Latina','code'=>'LT','region_id'=>15],
        //     ['name'=>'Lecce','code'=>'LE','region_id'=>7],
        //     ['name'=>'Lecco','code'=>'LC','region_id'=>9],
        //     ['name'=>'Livorno','code'=>'LI','region_id'=>5],
        //     ['name'=>'Lodi','code'=>'LO','region_id'=>10],
        //     ['name'=>'Lucca','code'=>'LU','region_id'=>5],
        //     ['name'=>'Macerata','code'=>'MC','region_id'=>3],
        //     ['name'=>'Mantova','code'=>'MN','region_id'=>10],
        //     ['name'=>'Massa-Carrara','code'=>'MS','region_id'=>5],
        //     ['name'=>'Matera','code'=>'MT','region_id'=>7],
        //     ['name'=>'Messina','code'=>'ME','region_id'=>1],
        //     ['name'=>'Milano','code'=>'MI','region_id'=>9],
        //     ['name'=>'Modena','code'=>'MO','region_id'=>10],
        //     ['name'=>'Monza e Brianza','code'=>'MB','region_id'=>9],
        //     ['name'=>'Napoli','code'=>'NA','region_id'=>6],
        //     ['name'=>'Novara','code'=>'NO','region_id'=>2],
        //     ['name'=>'Nuoro','code'=>'NU','region_id'=>12],
        //     ['name'=>'Olbia-Tempio','code'=>'OT','region_id'=>12],
        //     ['name'=>'Oristano','code'=>'OR','region_id'=>12],
        //     ['name'=>'Padova','code'=>'PD','region_id'=>11],
        //     ['name'=>'Palermo','code'=>'PA','region_id'=>1],
        //     ['name'=>'Parma','code'=>'PR','region_id'=>10],
        //     ['name'=>'Pavia','code'=>'PV','region_id'=>9],
        //     ['name'=>'Perugia','code'=>'PG','region_id'=>3],
        //     ['name'=>'Pesaro e Urbino','code'=>'PU','region_id'=>3],
        //     ['name'=>'Pescara','code'=>'PE','region_id'=>15],
        //     ['name'=>'Piacenza','code'=>'PC','region_id'=>10],
        //     ['name'=>'Pisa','code'=>'PI','region_id'=>5],
        //     ['name'=>'Pistoia','code'=>'PT','region_id'=>5],
        //     ['name'=>'Pordenone','code'=>'PN','region_id'=>11],
        //     ['name'=>'Potenza','code'=>'PZ','region_id'=>7],
        //     ['name'=>'Prato','code'=>'PO','region_id'=>5],
        //     ['name'=>'Ragusa','code'=>'RG','region_id'=>1],
        //     ['name'=>'Ravenna','code'=>'RA','region_id'=>10],
        //     ['name'=>'Reggio Calabria','code'=>'RC','region_id'=>14],
        //     ['name'=>'Reggio Emilia','code'=>'RE','region_id'=>10],
        //     ['name'=>'Rieti','code'=>'RI','region_id'=>15],
        //     ['name'=>'Rimini','code'=>'RN','region_id'=>10],
        //     ['name'=>'Roma','code'=>'RM','region_id'=>15],
        //     ['name'=>'Rovigo','code'=>'RO','region_id'=>10],
        //     ['name'=>'Salerno','code'=>'SA','region_id'=>6],
        //     ['name'=>'Medio Campidano','code'=>'VS','region_id'=>12],
        //     ['name'=>'Sassari','code'=>'SS','region_id'=>12],
        //     ['name'=>'Savona','code'=>'SV','region_id'=>2],
        //     ['name'=>'Siena','code'=>'SI','region_id'=>5],
        //     ['name'=>'Siracusa','code'=>'SR','region_id'=>1],
        //     ['name'=>'Sondrio','code'=>'SO','region_id'=>9],
        //     ['name'=>'Taranto','code'=>'TA','region_id'=>7],
        //     ['name'=>'Teramo','code'=>'TE','region_id'=>15],
        //     ['name'=>'Terni','code'=>'TR','region_id'=>3],
        //     ['name'=>'Torino','code'=>'TO','region_id'=>2],
        //     ['name'=>'Trapani','code'=>'TP','region_id'=>1],
        //     ['name'=>'Trento','code'=>'TN','region_id'=>11],
        //     ['name'=>'Treviso','code'=>'TV','region_id'=>11],
        //     ['name'=>'Trieste','code'=>'TS','region_id'=>11],
        //     ['name'=>'Udine','code'=>'UD','region_id'=>11],
        //     ['name'=>'Varese','code'=>'VA','region_id'=>9],
        //     ['name'=>'Venezia','code'=>'VE','region_id'=>11],
        //     ['name'=>'Verbano-Cusio-Ossola', 'code' => 'VB', 'region_id' => 2],
        //     ['name' => 'Vercelli', 'code' => 'VC', 'region_id' => 2],
        //     ['name' => 'Verona', 'code' => 'VR', 'region_id' => 8],
        //     ['name' => 'Vibo Valentia', 'code' => 'VV', 'region_id' => 14],
        //     ['name' => 'Vicenza', 'code' => 'VI', 'region_id' => 8],
        //     ['name' => 'Viterbo', 'code' => 'VT', 'region_id' => 15],
        // ];

        // foreach ($provinces as $province) {
        //     Province::create($province);
        // }
    }
}
